class Solution {
    public static void main(String[] args) {
       
        int distanceToTheMoon = 384400;
       
        int distanceToTheMars = 225000000;
        
      
        System.out.println("Is Distance To The Moon Less Than 1 million Km ? "+(distanceToTheMoon < 1000000));
       
        System.out.println("Is Distance To The Mars Greater Than Distance To The Moon ? "+ (distanceToTheMars > distanceToTheMoon));
        
    }
}
